let Name = "Marriet Aho";
console.log(Name);
let Age = 89;
console.log(Age);
let sum = 10 + 15;
console.log(sum);
let difference = 20 - 5;
console.log(difference);
let divide = 50 / 5;
console.log(divide);
let product = 7 * 6;
console.log(product);
let remainder = 15 % 4;
console.log(remainder);
let isStudent = false;
console.log(isStudent);
let variable = 150;
console.log(false); 
variable = "Hello, Where is my money?";
console.log(variable);