let myName = "Marriet Aho";
console.log(myName);
let myAge = 27;
console.log(myAge);
let sum = 10 + 15;
console.log(sum);
let difference = 20 - 5;
console.log(difference);
let quotient = 50 / 5;
console.log(quotient);
let product = 7 * 6;
console.log(product);
let remainder = 15 % 4;
console.log(remainder);
let isStudent = false;
console.log(isStudent);
let variable = 100;
console.log(typeof variable); 
variable = "Hello, World!";
console.log(typeof variable);